name: unet
dim: 512
init_dim: null
out_dim: 512
dim_mults: [1,2,2,4]
channels: 512
self_condition: False
resnet_block_groups: 8
learned_variance: False
learned_sinusoidal_cond: False
random_fourier_features: False
learned_sinusoidal_dim: 16

# padding
pad_in_model: 23


is_conditional: true
add_condition: false
scale_condition: true
condition_is_attention: false

