name: uvit
extras: 256 # the image features
len_latents: 73 # the length of the latents
embed_dim: 256
depth: 8
num_heads: 8
mlp_ratio: 4.0
qkv_bias: false
qk_scale: null
norm_layer: LayerNorm 
mlp_time_embed: true
use_checkpoint: false
skip: true
scale_y: false