name: w_plus_img_cams_ids_0.7_500k_final
path: ${env.datasets_dir}/${dataset.name}
w_path: ${dataset.path}/samples
img_path: ${dataset.path}/images
stats_path: ${dataset.path}/stats.pt
base_seq_len: 73
attr_seq_len: 0
padding: [0,0]

# Default parameters
image_size: 256
normalize_w: True
normalize_image: True

# TODO:
# FFHQ parameters
real_img_path: ${env.datasets_dir}/ffhq_512_posed_eg3d
real_mesh_path: ${env.datasets_dir}/ffhq_512_posed_eg3d/deca_results_unposed

# When used with slurm, this will take the dataset from `path_for_slurm_job`
# and will copy it into the `path` location
path_for_slurm_job: ${env.datasets_dir}/${dataset.name}

# meshes and stuff
obj_path: ${env.project_path}/data/demo/demo.obj
lms_path: ${env.project_path}/data/demo/demo_kpt2d.txt
lms_cond: True

type: w_data
mode: train