
per_gpu_batch_size: 64
batch_size: 64 # Total batch size  # TODO
test_batch_gpu: 64 # Batch size at test time

# Additional training parameters.
resume: latest # Resume from given network pickle

# lr schedule
cycle_momentum: true
div_factor: 25.0 # default value
final_div_factor: 1e4 # default value
pct_start: 0.2 # default value
three_phase: false # default value
lr: 0.0001

# Misc settings.
desc: null # String to include in result dir name
metrics: fid2k_full,nfs256 # Quality metrics
main_metric: __pick_first__ # Takes the first metric among `metrics` as the main one to compute the best checkpoint
total_iter: 100000 # Total training duration
tick: 4 # How often to print progress
val_freq: 5000 # How often to compute metrics
snap: 5000 # How often to save snapshots
image_snap: 5000 # How often to save samples?
seed: 0 # Random seed
nobench: false # Disable cuDNN benchmarking
workers: 4 # DataLoader worker processes
dry_run: false # Print training options and exit