defaults:
  - env/base.yaml
  - env: raven

  - model/base.yaml
  - model: base

  - training/base.yaml
  - training: base

  - dataset/base.yaml
  - dataset: base

  - infra.yaml

# ----------------------------------------------------------------------------
# Wandb config
# ----------------------------------------------------------------------------
project: diffusion_face
notes: ""
