defaults:
  - env/base.yaml
  - env: raven

  - model/base.yaml
  - model: base

  - training/base.yaml
  - training: base

  - dataset/base.yaml
  - dataset: base

  - diffusion/base.yaml
  - diffusion: base

  - infra.yaml

  - conditioner/base.yaml
  - conditioner: deeplab

  - optimizer/base.yaml
  - optimizer: base

  - _self_
  
  # ----------------------------------------------------------------------------
  # Wandb config
  # ----------------------------------------------------------------------------
project: diffusion_face
notes: aa