path: ${env.datasets_dir}/${dataset.name}
seq_length: 336
timesteps: 1000
sampling_timesteps: 100
objective: 'pred_v'
beta_schedule: 'cosine'
beta_start: 0.0001
beta_end: 0.02
beta_s: 0.008
ddim_sampling_eta: 0.0
auto_normalize: True
is_self_denoising: False
loss_type: 'l1'
loss_kwargs: {}