python_bin: ${env.project_path}/env/bin/python
project_path: /home/parawr/Projects/Next3D
before_train_commands:
  - conda deactivate
  - source $HOME/.bashrc
  - module purge
  - module unload cuda
  - module load cmake
  - module load gcc/11.1.0
  - module load cudnn/8.8.1-cuda11.8.0  # because nvcc crashed 
  - conda activate /home/parawr/Projects/Next3D/env
  - pwd
  - python -c 'import torch; print("Number of GPUs available:", torch.cuda.device_count())'
# datasets_dir: /ibex/ai/home/parawr/Projects/diffusion/data
datasets_dir: /ibex/project/c2241/data/diffusion/
results_dir: /ibex/ai/home/parawr/Projects/diffusion/experiments
slurm_constraint: a100